package com.mercantil.operationsandexecution.crosscutting.restclients.models;

import lombok.AllArgsConstructor;
import lombok.Getter;

/**
 * Canonical list of log actions used to categorize and search telemetry/logs.
 * The {@link #logString} is the human-readable label emitted in logs.
 *
 * @since 1.0
 */
@Getter
@AllArgsConstructor
public enum EnumActionLogs {

    EXCEPTION_HTTP_CLIENT_ERROR("EXCEPTION HTTP CLIENT ERROR"),
    RETRIEVE_POS_REPORT("RETRIEVE POS REPORT MERCHANT ACQUIRING FACILITY"),
    EXCEPTION_METHOD_ARGUMENT_NOT_VALID_ERROR("EXCEPTION METHOD ARGUMENT NOT VALID ERROR"),
    EXCEPTION_ILLEGAL_ARGUMENT_ERROR("EXCEPTION ILLEGAL ARGUMENT ERROR"),
    EXCEPTION_MISSING_REQUEST_HEADER_ERROR("EXCEPTION MISSING REQUEST HEADER ERROR"),
    EXCEPTION_NO_RESOURCE_FOUND_EXCEPTION_ERROR("EXCEPTION NO RESOURCE FOUND EXCEPTION ERROR"),
    EXCEPTION_CAPTURED_GENERIC("EXCEPTION CAPTURED GENERIC"),
    EXCEPTION_CREATE_KEY_STORE_ERROR("EXCEPTION CREATE KEY STORE ERROR"),
    EXCEPTION_SANITIZER_TWO_ERROR("EXCEPTION SANITIZER TWO ERROR"),
    RETRIEVE_POS_TERMINALS("RETRIEVE POS TERMINALS FOR EXISTING CLIENT"),
    NOT_IDENTIFIED("Servicio ejecutado no capturado"),
    SEND_NOTIFICATION_EMAIL("SEND NOTIFICATION BY EMAIL"),
    SEND_NOTIFICATION_SMS("SEND NOTIFICATION BY SMS"),
    SAVE_TOKEN_CACHE("SAVE TOKEN IN CACHE SERVICE"),
    GET_TOKEN_CACHE("GET TOKEN FROM CACHE SERVICE"),
    SEND_TRANSACTION("SEND TRANSACTION EVENT"),
    GENERIC_ERROR("GENERIC ERROR");

    /**
     * Human-readable action label to write in logs.
     */
    private final String logString;
}
